### ISSUE TITLE
Feature Request: endpoint for shorter quotes

### ISSUE THREAD

**Issue by rs7q5** [alakhpc/tv-quotes-api#2]
Just found this API and it's awesome!!

Is there any chance there can be an endpoint for one line or one person quotes? Some of the quotes are full scenes and are really long, so being able to return some that are shorter would be cool.

On a separate note are you planning on adding more shows or taking requests for new shows anytime soon?

**Comment by jepcd** [comment]
Added :), You can now use ?short=true on any endpoint

Not adding any more shows as of now.

**Comment by rs7q5** [comment]
I didn't realize that fix was going to be so easy! Thanks!

**Comment by rs7q5** [comment]
I know I closed this, but does it just return quotes involving one character or just the first part of the quotes? 

I assume the former?

**Comment by jepcd** [comment]
Quotes with just one character

**Comment by rs7q5** [comment]
Awesome! Thanks!
